satanic_buffs = {
    "Loot Goblin I": "+1 Maximum Loot from Enemy Killed",
    "Loot Goblin II": "+2 Maximum Loot from Enemy Killed",
    "Rune Master": "15% + (2.5% per sub difficulty level) Increased Rune Drop Chance",
    "Gold Hunger": "Gold from monster kills increased by 40% + (8.75% per sub difficulty level)",
    "Heroic Windfall": "Heroic Item drop chances increased by 3% + (3% per sub difficulty level)",
    "Angelic Fortune": "Angelic Item drop chances increased by 25% + (7.5% per sub difficulty level)",
    "Zephys Grace": "Movement Speed increased by 50%",
    "Fury of Tempest": "Attack Speed increased by 60%",
    "Rapid Casting": "Faster Cast Rate increased by 60%",
    "Onslaught": "Attack Damage increased by 100%",
    "Nether Surge": "Magic Skill Damage increased by 40%",
    "Relic Keepers": "Ancient monsters have a 2% chance to drop a relic on death",
    "Goblin's Greed": "Champion+ monsters have a 0.5% chance to summon a Treasure Goblin on death",
    "Artifact Digger": "+55% Magic Find + (5% per sub difficulty level)",
    "Artifact Seeker": "+110% Magic Find + (10% per sub difficulty level)",
    "Artifact Excavator": "+170% Magic Find + (20% per sub difficulty level)",
    "Recruit": "+10% Experience Gain + (2.5% per sub difficulty level)",
    "Combat Training": "+15% Experience Gain + (3.75% per sub difficulty level)",
    "Battle Scarred": "+20% Experience Gain + (5% per sub difficulty level)",
    "Clairvoyance": "All recovery increased by 100% (Includes: Mana per hit, Life per hit, Mana and Life Replenish etc)",
    "Aftermath": "Monsters have a 3% chance to summon a Legion version of them on death",
    "Deep Cuts": "Critical Strike damage increased by 200%",
    "Old Town": "+15% chance for Ancient Packs",
    "Terror Zone": "+25% chance for Ancient Packs",
    "Fields of Carnage": "+30% chance for Ancient Packs",
}